import "@/styles/globals.css"
import type { Metadata } from "next";
import { Poppins as FontSans } from "next/font/google"
import { ThemeProvider } from "@/components/theme-provider";

import { cn } from "@/lib/utils"

const fontSans = FontSans({
  weight: ['400', '500', '600', '700'],
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className="scroll-smooth">
      <body className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.className
        )}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </body>
    </html>
  );
}
